### ISSUE TITLE
Suggestion: Be able to copy from chatbox

### ISSUE THREAD

**Issue by tfcmahmoud** [astra1dev/AUnlocker#1]
I would suggest you add the ability of Ctrl+A in chat

**Comment by astra1dev** [comment]
First off thanks for your suggestion.

What would Ctrl + A do?

**Comment by tfcmahmoud** [comment]
it selects all text that you wrote, so you can delete faster or just copy

**Comment by astra1dev** [comment]
Okay that is a good suggestion. Will take a look if it's possible, then i will get back to you.

**Comment by astra1dev** [comment]
Sadly, it's not possible to select / copy text FROM the chatbox, its only possible to paste INTO it because the chatbox has limited capabilities. 

In my opinion thats not much of an issue tho... 
let me know if you have any other suggestion / question

**Comment by astra1dev** [comment]
Never mind, found a way to copy from the chatbox. 
You won't need Ctrl+A for that, instead, when the text area is focused and you press Ctrl+C, the whole string from the chatbox gets copied into your clipboard.

I will commit + update AUnlocker soon.
