### ISSUE TITLE
Error while trying to play online

### ISSUE THREAD

**Issue by HedgeX1399** [astra1dev/AUnlocker#10]
in the steam instance of the game, while using AUnlocker, the online section is unlocked yet while trying to join by code or view avaliable servers i encounter an "Unauthorized - user is not logged in" error.
is this supposed to be like this?

**Comment by astra1dev** [comment]
Are you still having this issue? New among us update just released

**Comment by kroesufos** [comment]
> Are you still having this issue? New among us update just released

Im having the same issue, im on linux and i followed both of the steps, i use bottles as a proton executor, maybe the winhttp dll is a problem?

**Comment by kroesufos** [comment]
> Are you still having this issue? New among us update just released

Also when the proton game redirects me to my REAL browser, my REAL browser cant find the link between among us and my browser

**Comment by astra1dev** [comment]
When the game launches, there should be a console window coming up. Are there any errors shown (in red)?

**Comment by kroesufos** [comment]
> When the game launches, there should be a console window coming up. Are there any errors shown (in red)?

Let me see, ty for answering fast!

**Comment by kroesufos** [comment]
![image](https://github.com/user-attachments/assets/06442f57-a5fd-42e5-b6e9-45367cccdf25)

yea

**Comment by astra1dev** [comment]
that does not look good haha, it's probably an issue with proton but not sure. can you try switching to a different proton version? https://www.protondb.com/app/945360 here some people suggest Proton GE (Glorious Eggroll)

**Comment by kroesufos** [comment]
> that does not look good haha, it's probably an issue with proton but not sure. can you try switching to a different proton version? https://www.protondb.com/app/945360 here some people suggest Proton GE (Glorious Eggroll)

![image](https://github.com/user-attachments/assets/e672a8a8-2388-409a-bf6f-d546054b04ee)
ehh..

**Comment by astra1dev** [comment]
if that doesn't work maybe try the following: 
1. Install protontricks and run `protontricks --gui` 
2. Choose `Select the default wineprefix` and click OK.
3. Select `Run winecfg` and click OK.
4. In the Wine configuration window, navigate to the `Libraries` tab.
5. Enter `winhttp` into the `New override for library` input field (without quotation marks).
6. Click Add and then Apply. Now launch the game from Steam.

**Comment by kroesufos** [comment]
> if that doesn't work maybe try the following:
> 
> 1. Install protontricks and run `protontricks --gui`
> 2. Choose `Select the default wineprefix` and click OK.
> 3. Select `Run winecfg` and click OK.
> 4. In the Wine configuration window, navigate to the `Libraries` tab.
> 5. Enter `winhttp` into the `New override for library` input field (without quotation marks).
> 6. Click Add and then Apply. Now launch the game from Steam.
>    (as you said earlier maybe winhttp is the issue so this might fix it)

i tried with and without the dll override, but its just not working :/
![image](https://github.com/user-attachments/assets/95a14e73-c410-4407-9b54-55dfed7f805e)

**Comment by kroesufos** [comment]
Ok ill try that then

**Comment by kroesufos** [comment]
Nah, same thing

**Comment by astra1dev** [comment]
Does the issue appear when playing without the mod?

**Comment by kroesufos** [comment]
It seems like proton and not even steam combatibility tool are working, when the auth login pages appears it just runs xdg-open, wich is used to open files, links, etc, and doesnt run the proton process, heres the file among us tries to open: amongus://itchio/callback#state=1310155285396405480&access_token=(my access token).

**Comment by kroesufos** [comment]
> Does the issue appear when playing without the mod?

Yep, with and without the mod

**Comment by astra1dev** [comment]
Oh then this is not related to the mod at all. 
I really don't know how to fix this issue then. Sorry. You should do some research on your own and maybe open a ticket on Among Us Helpdesk or something... usually Among Us runs on Linux with Proton / Wine without any problems....

**Comment by kroesufos** [comment]
Thanks!

**Comment by astra1dev** [comment]
@HedgeX1399 try the fixes i sent in https://github.com/astra1dev/AUnlocker/issues/18
