### ISSUE TITLE
no work 

### ISSUE THREAD

**Issue by Madoka1308** [astra1dev/AUnlocker#11]
hi i put the zip on folder but when i start the game this dosn't work

**Comment by astra1dev** [comment]
Read the instructions carefully please. You need to extract the .zip before pasting it in the among us folder.

**Comment by Madoka1308** [comment]
i do in witch folder i put the extract ?

**Comment by astra1dev** [comment]
Please, I'm asking you again, to read the instructions carefully. Come back if you have any more issues.

**Comment by astra1dev** [comment]
Hello? Did you finally read the instructions?
