### ISSUE TITLE
AUnlocker is not working on cracked version

### ISSUE THREAD

**Issue by ineedhelpfromwherewherepls** [astra1dev/AUnlocker#14]
I extracted and did everything like the instructions said but I didn't get the cosmetics. I play on the 2024.6.18 version so idk if there's a issue with that version but yeah can someone tell me how to fix it

**Comment by astra1dev** [comment]
can you send a screenshot of your among us game folder?

**Comment by ineedhelpfromwherewherepls** [comment]
yessir here it is 
![Screenshot 2024-07-17 190809](https://github.com/user-attachments/assets/ddca1a0f-727c-4bc3-9d1f-20e04146caac)

**Comment by astra1dev** [comment]
do you have the game on microsoft store or did you download a cracked version of among us? because only steam and epic are supported.... (this is btw also the case for other mods using BepInEx, not only aunlocker)

also, you have a lot more files in that folder than there should be usually

**Comment by ineedhelpfromwherewherepls** [comment]
Yeah i cracked it, so it means I cant use it? and if the answer is no you cant use it are you ever gonna release the cracked version?

**Comment by astra1dev** [comment]
Cracked version doesn't work unfortunately. you can also check out other among us mods like malumMenu, they all only support steam and epic. 

I advise you to just buy the game on steam, its literally just a few bucks, not like elden ring or forza or some crazy expensive game

**Comment by ineedhelpfromwherewherepls** [comment]
oh alr thanks i will buy the game and try it out

**Comment by astra1dev** [comment]
Have you tried it out yet?
