### ISSUE TITLE
Can't Log onto my Account

### ISSUE THREAD

**Issue by therealvib3z** [astra1dev/AUnlocker#18]
I'm playing Among Us (through Steam) on the newest version on my Windows 11 PC, and I've installed the mod, as usual like all my other mods, into a seperate folder, and everytime I try to log in, it hits me with the Error: SteamworksAuthFail, so I'm not sure what I'm doing wrong here.

![image_2024-08-05_201917193](https://github.com/user-attachments/assets/c87fc4bf-3f85-4d83-90f2-f97fd3845f26)

**Comment by astra1dev** [comment]
What separate folder? Can you send a screenshot? 
Are you sure you are launching the game via Steam and not via the .exe? 
Does Among Us work for you without having any Mods installed? 
(sorry thats a lot of questions 😂)

**Comment by astra1dev** [comment]
![image](https://github.com/user-attachments/assets/073b3a3a-4a84-4e2a-a933-c5114d80a735)
I was able to reproduce your issue by launching the game's .exe file and not via Steam.

**Comment by astra1dev** [comment]
Also try editing the file: `[YOUR_AMONGUS.EXE_LOCATION/BepInEx/config/AUnlocker.cfg` and change the line `AccountPatches = true` to `AccountPatches = false`
