### ISSUE TITLE
[PLEASE READ] Innersloth patched some things

### ISSUE THREAD

**Issue by astra1dev** [astra1dev/AUnlocker#2]
Innersloth just upgraded their anticheat.
The current method AUnlocker is using to bypass anticheat is not working anymore.
Sending long messages or special characters will get you kicked from the lobby.

I am aware of this situation, but it seems there is no fix for it. 
Will probably remove the UnlockChat feature next update :( 

Have a nice day

**Comment by nonameusers134** [comment]
2024.2.8 version, update pls!!!!
