### ISSUE TITLE
Cannot log in to account when in epic games

### ISSUE THREAD

**Issue by Pr0j3ct01** [astra1dev/AUnlocker#21]
there is another issue that i saw of a person that had the same thing as me but he was using the steam version, for me i am using the epic games version and i have this issue

**Comment by astra1dev** [comment]
Try launching the game from the launcher and not via the .exe this should fix it. Also new among us update, download it and see if it works.

**Comment by Pr0j3ct01** [comment]
i was launching the game from the launcher but it said failed could not connect to among us account

**Comment by Pr0j3ct01** [comment]
(error: friendcodefail)

**Comment by Pr0j3ct01** [comment]
i have even tried to switch versions for aunlocker but it didnt work

**Comment by Pr0j3ct01** [comment]
> Try launching the game from the launcher and not via the .exe this should fix it. Also new among us update, download it and see if it works.

any way i can fix this??

**Comment by astra1dev** [comment]
Does this issue occur when playing without any mods? Innersloth has a help page for this issue: https://innersloth.zendesk.com/hc/en-us/articles/24995238715028--Error-Friendcode-Fail

**Comment by Pr0j3ct01** [comment]
> Does this issue occur when playing without any mods? Innersloth has a help page for this issue: https://innersloth.zendesk.com/hc/en-us/articles/24995238715028--Error-Friendcode-Fail

yes it does, i only put in the aunlocker files without anything else and thats what i get everytime i launch the game

**Comment by astra1dev** [comment]
Are you sure you put in the files correctly? Check the screenshot from the FAQ on the README for how it should look like

**Comment by Pr0j3ct01** [comment]
> Are you sure you put in the files correctly? Check the screenshot from the FAQ on the README for how it should look like

yes it does

**Comment by Pr0j3ct01** [comment]
> Are you sure you put in the files correctly? Check the screenshot from the FAQ on the README for how it should look like

i think the problem is with the account prefrences on aunlocker, is there a way just to get the cosmetics???

**Comment by Pr0j3ct01** [comment]
> Are you sure you put in the files correctly? Check the screenshot from the FAQ on the README for how it should look like

fixed it, turns out the account features were messing up my log in, thanks for the help.

**Comment by Pr0j3ct01** [comment]
> can you specify what you did to fix it? then i could publish a fix that changes the default value for account patches

i thought bepinex.cfg was the cfg for changing the features but turns out you have to join the game then check the file, so i just went over to AUnlocker.cfg and changed the chat and account features to false

**Comment by astra1dev** [comment]
Makes sense, thank you. v1.1.6 will add more config options and also improve the default settings, so no one should get any sign-in errors anymore.
