### ISSUE TITLE
Error Steamworks Auth Fail.

### ISSUE THREAD

**Issue by 0Snake420** [astra1dev/AUnlocker#22]
**Describe the bug**
When I log onto among us it fails with au unlocker.

**To Reproduce**
Update to latest au unlocker.

**Expected behavior**
Steamworks auth fail.

**Screenshots**
Don't have screenshots but pls email me if im doing something wrong.

**System Information (please complete the following information):**
 - Operating System: [Windows 11]
 - Game version [8/13/2024]
 - AUnlocker version [1.1.6]

**Additional context**
Pls lmk if yours is working and if im doing something wrong.

**Comment by 0Snake420** [comment]
I do have in seperate folder, but still operating thru steam. I keep my regular among us folder seperate from this one, my tohe folder seperate, and this one in its own. It was working before among us and au unlockers latest updates. Regular among us is working.

**Comment by astra1dev** [comment]
delete the AUnlocker.cfg file located in BepInEx/config then restart the game and see if it works

**Comment by astra1dev** [comment]
Also try starting the game via steam and not via the .exe file (you could also create a file called `steam_appid.txt` containing the following: `945360`

**Comment by 0Snake420** [comment]
Running the game manually via steam worked. I'm going to need the configs in the future for town of host enhanced so I wont touch that. I think the only error running town of host enhanced and au unlocked together is they both run a command that bypasses chat and copy and paste but with your configs I can turn that off. But everything is in working order now, thanks!

**Comment by astra1dev** [comment]
Glad i could help :) 
Mods for Among Us generally don't really work well with each other, thats why I added the config system so you can technically disable every patch to eliminate issues with other mods.

**Comment by astra1dev** [comment]
Glad i could help :) 
Mods for Among Us generally don't really work well with each other, thats why I added the config system so you can technically disable every patch to eliminate issues with other mods.

**Comment by astra1dev** [comment]
Btw you might want to remove your email from your post
