### ISSUE TITLE
Commands in TOHE

### ISSUE THREAD

**Issue by CYCLOLCYC** [astra1dev/AUnlocker#23]
When I use TOHE with this, the commands don't work.

**Comment by astra1dev** [comment]
Try disabling the ChatPatches in the settings file found here: `{YOUR_AMONG_US_FOLDER}/BepInEx/plugins/AUnlocker.cfg`

**Comment by astra1dev** [comment]
Did it work? @CYCLOLCYC

**Comment by CYCLOLCYC** [comment]
It worked, thanks :D
