### ISSUE TITLE
Why it have a cmd run?

### ISSUE THREAD

**Issue by MinecraftNguyen** [astra1dev/AUnlocker#24]
I don't know why it got a CMD.exe? can you remove this?

**Comment by astra1dev** [comment]
Oh im sorry, you can totally turn it off. Go to `[YOUR_AMONG_US_GAME_LOCATION]/BepInEx/config/BepInEx.cfg` and set `Logging.Console` to `false`. Let me know if it worked for you. Have a nice day.
